name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: invoice
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create startup command file
      run: |
        echo "gunicorn -k uvicorn.workers.UvicornWorker --timeout 1800 --graceful-timeout 1800 --keep-alive 1800 --bind=0.0.0.0:8000 main:app" > startup.txt

    - name: Generate deployment package
      run: |
        zip -r package.zip . -x "antenv/*"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      timeout-minutes: 30
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package.zip